image: docker:latest
services:
  - docker:dind

cache:
  key: "$CI_JOB_NAME"
  untracked: true

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test
  - release
  - deploy
  - cleanup

# docker-compose does not come with the image normally, so lets add it
before_script:
  - apk add --update python py-pip python-dev && pip install docker-compose
  - docker version
  - docker-compose version
  - docker info

build:
  stage: build
  script:
    - docker-compose pull
    - docker-compose build
    - docker-compose tag $CI_JOB_NAME

test_front_end:
  stage: test
  script:
    - docker-compose run frontend npm run lint
    - docker-compose run frontend npm run test

test_scraper:
  stage: test
  script:
    - docker-compose run scraper pytest

# release_containers:
#   stage: release
#   script:
#     - docker-compose pull -t $CI_JOB_NAME
#     - docker-compose tag $CI_JOB_NAME latest
#     - docker-compose push
#   only:
#     - master

release_front_end:
  stage: release
  script:
    - mkdir ./front_build
    - BUILD="PROD" docker-compose run -v "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"/front_build:/go/src/app/dist frontend:$CI_JOB_NAME
  only:
    - master

# deploy_containers:
#   stage: deploy
#   script:
#     - docker-compose push
#   only:
#     - master

deploy_front_end:
  stage: deploy
  variables:
    CDN_BUCKET: "s3://cdn.dailywoof.space/"
    INDEX_BUCKET: "s3://dailywoof.space/"
  script:
    - pip install awscli
    - aws s3 cp ./front_build $CDN_BUCKET --recursive # Javascript and css
    - aws s3 cp ./front_build/index.html $INDEX_BUCKET # index.html
  only:
    - master

cleanup:
  stage: cleanup
  script:
    - docker-compose down
    - rm -rf ./front_build
