image: docker:latest

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - build
  - test
  - cleanup

build:
  stage: build
  script:
    - apk add --update python py-pip python-dev && pip install docker-compose
    - docker version
    - docker-compose version
    - docker info
    - docker-compose up -d

lint:
  stage: test
  script:
    - docker-compose run web npm run lint
test_front_end:
  stage: test
  script:
    - docker-compose run web npm run lint
    - docker-compose run web npm run test
test_scraper:
  stage: test
  script:
    - docker-compose run scraper pytest

cleanup:
  stage: cleanup
  script:
    - docker-compose down
