image: docker:latest

variables:
  DOCKER_DRIVER: overlay2

services:
- docker:dind

before_script:
  - apk add --update python py-pip python-dev && pip install docker-compose
  - docker version
  - docker-compose version
  - docker info
  - docker-compose up -d
lint:
  script:
    - npm run lint
test_front_end:
  script:
    - docker-compose run web npm run lint
    - docker-compose run web npm run test
test_scraper:
  script:
    - docker-compose run scraper pytest
after_script:
  - docker-compose down
