image: docker:latest

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - test
  - build
  - cleanup

# docker-compose does not come with the image normally, so lets add it
before_script:
  - apk add --update python py-pip python-dev && pip install docker-compose
  - docker version
  - docker-compose version
  - docker info

test_front_end:
  stage: test
  script:
    - docker-compose run frontend npm run lint
    - docker-compose run frontend npm run test

test_scraper:
  stage: test
  script:
    - docker-compose run scraper pytest

cleanup:
  stage: cleanup
  script:
    - rm -rf ./front_build
    - docker-compose down

build_front_end:
  stage: build
  environment: production
  script:
    - mkdir ./front_build
    - docker-compose build
    - BUILD="PROD" docker-compose run -v "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"/front_build:/go/src/app/dist frontend
    - pip install awscli
    - aws s3 cp ./front_build s3://cdn.dailywoof.space/ --recursive
