image: docker:latest

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - test
  - build
  - cleanup

# docker-compose does not come with the image normally, so lets add it
before_script:
  - apk add --update python py-pip python-dev && pip install docker-compose
  - docker version
  - docker-compose version
  - docker info

test_front_end:
  stage: test
  script:
    - docker-compose run web npm run lint
    - docker-compose run web npm run test

test_scraper:
  stage: test
  script:
    - docker-compose run scraper pytest

cleanup:
  stage: cleanup
  script:
    - docker-compose down

build:
  stage: build
  script:
    - docker-compose build
