version: "3.1"
services:
  phantomjs:
    build: phantomjs
    deploy:
      restart_policy:
        condition: on-failure
  web:
    build: web
    links:
      - redis
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - PORT=8080
    volumes:
      - ./dictionary:/go/src/app/dictionary
      - web-stuff:/go/src/app/dist
  scraper:
    build: src
    command: python app.py
    depends_on:
      - phantomjs
      - redis
    links:
      - phantomjs:browser
      - redis
    deploy:
      restart_policy:
        condition: on-failure
  images:
    build: images
    links:
      - redis
    depends_on:
      - redis
    environment:
      - IMGUR_ID=__Key_goes_here__
      - IMGUR_SECRET=__Secret_goes_here__
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-db:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
  frontend:
    build: frontend
    volumes:
      - web-stuff:/go/src/app/dist
volumes:
  web-stuff:
  redis-db:
