version: "3.1"
services:
  phantomjs:
    image: superpolkadance/phantomjs:1.0
    deploy:
      restart_policy:
        condition: on-failure
  redis:
    image: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - redis-db:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    deploy:
      restart_policy:
        condition: on-failure
  web:
    build: web
    command: ./bin/app
    links:
      - redis
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - PORT=8080
    volumes:
      - ./dictionary:/go/src/app/dictionary
      - web-stuff:/go/src/app/dist
  scraper:
    build: scraper
    command: python app.py
    depends_on:
      - phantomjs
      - redis
    links:
      - phantomjs:browser
      - redis
    deploy:
      restart_policy:
        condition: on-failure
  images:
    build: images
    command: python test.py
    links:
      - redis
    depends_on:
      - redis
    deploy:
      restart_policy:
        condition: on-failure
  frontend:
    build: frontend
    volumes:
      - web-stuff:/go/src/app/dist
volumes:
  web-stuff:
  redis-db:
