version: "3.5"
volumes:
  web-stuff:
networks:
  net:
services:
  rabbitmq-service:
    image: rabbitmq:3.7.2
    hostname: my-rabbit
    networks:
      net:
  redis-service:
    image: redis
    command: redis-server
    networks:
      net:
  web:
    image: superpolkadance/dailywoofweb
    build: web
    command: ./bin/app
    networks:
      net:
        aliases:
          - redis
    ports:
      - "8080:8080"
    depends_on:
      - redis-service
    environment:
      - PORT=8080
    volumes:
      - web-stuff:/go/src/app/dist
  natlang:
    image: superpolkadance/dailywoofnlp
    build: natlang
    command: python app.py
    depends_on:
      - rabbitmq-service
    networks:
      net:
  images:
    image: superpolkadance/dailywoofimages
    build: images
    command: python app.py
    networks:
      net:
    depends_on:
      - redis-service
      - rabbitmq-service
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
  frontend:
    image: superpolkadance/dailywooffrontend
    build: frontend
    command: npm run build
    volumes:
      - web-stuff:/go/src/app/dist
    environment:
      - BUILD=$BUILD
  scraper:
    image: superpolkadance/dailywoofscraper
    build: scraper
    command: python3.6 app.py
    depends_on:
      - rabbitmq-service
      - redis-service
    networks:
      net:
