apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: dailywoof-space
  namespace: default
spec:
  secretName: dailywoof-space-tls
  issuerRef:
    name: ca-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: Issuer
  commonName: dailywoof.space
  dnsNames:
  - dailywoof.space
  - cdn.dailywoof.space
  - api.dailywoof.space
  - assets.dailywoof.space
  - www.dailywoof.space
