apiVersion: v1
kind: Service
metadata:
  name: woof-api
spec:
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: woof-api
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: woof-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: woof-api
    spec:
      containers:
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:1
        args: [
          "--http_port", "8081",
          "--backend", "127.0.0.1:8080",
          "--service", "echo-api.endpoints.dailywoof-197400.cloud.goog",
          "--version", "2018-03-10r0",
        ]
        ports:
          - containerPort: 8081
      - name: dailywoofapi
        image: superpolkadance/dailywoofweb
        ports:
          - containerPort: 8080
        args:
          - ./bin/app
