apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scrape
spec:
  schedule: "@daily"
  jobTemplate:
    spec:
      template:
        spec:
          # https://cloud.google.com/kubernetes-engine/docs/how-to/node-taints
          tolerations:
            - key: cpu
              operator: Equal
              value: power
              effect: NoSchedule
          containers:
            - name: natlang
              image: superpolkadance/dailywoofnlp:latest
              args:
                - timeout
                - "1800"
                - python
                - app.py
            - name: scraper
              image: superpolkadance/dailywoofscraper:latest
              args:
                - timeout
                - "1800"
                - python3.6
                - app.py
              resources:
                limits:
                  cpu: 800m
          restartPolicy: Never
