apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: images
spec:
  schedule: "@daily"
  jobTemplate:
    spec:
      template:
        spec:
          # https://cloud.google.com/kubernetes-engine/docs/how-to/node-taints
          tolerations:
            - key: image
              operator: Equal
              value: image
              effect: NoSchedule
          containers:
            - name: images
              image: superpolkadance/dailywoofimages:latest
              args:
                - python
                - app.py
              env:
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: aws-creds
                      key: id.txt
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: aws-creds
                      key: key.txt
          restartPolicy: Never
