apiVersion: v1
kind: ReplicationController
metadata:
  name: scraper-controller
spec:
  replicas: 1
  template:
    spec:
      tolerations:
        - key: power
          operator: Equal
          value: power
          effect: NoSchedule
      containers:
        - name: images
          image: superpolkadance/dailywoofimages:latest
          args:
            - python
            - app.py
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-creds
                  key: id.txt
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-creds
                  key: key.txt
