apiVersion: v1
kind: ReplicationController
metadata:
  name: natlang-controller
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: superpolkadance/dailywoofnlp:latest
          name: natlang
          args:
            - python
            - app.py
